# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0003_auto_20171123_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start',
            field=models.CharField(max_length=255),
        ),
    ]
